orcs:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "2222:22"
    - "5432:5432"
    - "9000:9000"
    - "6379:6379"
    - "9001:9001"
  volumes:
    - ../:/var/www/loo
    - ../logs:/var/log/supervisor
